name: Karate Test
run-name: Pipeline - from user @${{ github.actor }}

on:
  push:
    branches:
      - main
  
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Karate test
      run: mvn test -Dkarate.options="--tags @signup"

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: karate-report
        path: target/karate-reports
        retention-days: 30
